<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyName>SillyWars.Engine.Shared</AssemblyName>
  </PropertyGroup>

  <Target Name="ToUnity" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" 
          DestinationFolder="../../Assets/Plugins" />
  </Target>

</Project>
